//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Media_Downloader.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Media_Downloader.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Abrir Carpeta.
        /// </summary>
        public static string Abrir_Carpeta {
            get {
                return ResourceManager.GetString("Abrir Carpeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acerca de.
        /// </summary>
        public static string Acerca_de {
            get {
                return ResourceManager.GetString("Acerca de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar.
        /// </summary>
        public static string Actualizar {
            get {
                return ResourceManager.GetString("Actualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir Preset.
        /// </summary>
        public static string Añadir_Preset {
            get {
                return ResourceManager.GetString("Añadir Preset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a \n\nAlso tengo que hacer esto mas bonico.
        /// </summary>
        public static string Bonico {
            get {
                return ResourceManager.GetString("Bonico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Borrar.
        /// </summary>
        public static string Borrar {
            get {
                return ResourceManager.GetString("Borrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Borrar Preset.
        /// </summary>
        public static string Borrar_Preset {
            get {
                return ResourceManager.GetString("Borrar Preset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Convirtiendo Archivos.
        /// </summary>
        public static string Convirtiendo_Archivos {
            get {
                return ResourceManager.GetString("Convirtiendo Archivos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descargando archivos.
        /// </summary>
        public static string Descargando_archivos {
            get {
                return ResourceManager.GetString("Descargando archivos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descargar.
        /// </summary>
        public static string Descargar {
            get {
                return ResourceManager.GetString("Descargar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descargar Miniaturas.
        /// </summary>
        public static string Descargar_Miniaturas {
            get {
                return ResourceManager.GetString("Descargar Miniaturas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descargar Subtitulos.
        /// </summary>
        public static string Descargar_Subtitulos {
            get {
                return ResourceManager.GetString("Descargar Subtitulos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descargas.
        /// </summary>
        public static string Descargas {
            get {
                return ResourceManager.GetString("Descargas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desea borrar la preset:.
        /// </summary>
        public static string Desea_borrar_la_preset_ {
            get {
                return ResourceManager.GetString("Desea borrar la preset:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha habido un fallo en la ejecucion del programa.\n¿Quiere volver a intentar la descarga y guardar el resultado para poder revisarlo mas tarde?.
        /// </summary>
        public static string DownloadErrorMsg {
            get {
                return ResourceManager.GetString("DownloadErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en la descarga..
        /// </summary>
        public static string DownloadErrorTitle {
            get {
                return ResourceManager.GetString("DownloadErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empezar por:.
        /// </summary>
        public static string Empezar_por_ {
            get {
                return ResourceManager.GetString("Empezar por:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Español.
        /// </summary>
        public static string Español {
            get {
                return ResourceManager.GetString("Español", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha producido un error no controlado, el progama debe cerrarse.
        /// </summary>
        public static string ExceptionMsg {
            get {
                return ResourceManager.GetString("ExceptionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error no controlado.
        /// </summary>
        public static string ExceptionTitle {
            get {
                return ResourceManager.GetString("ExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Extras.
        /// </summary>
        public static string Extras {
            get {
                return ResourceManager.GetString("Extras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fallo en la descarga.
        /// </summary>
        public static string Fallo_en_la_descarga {
            get {
                return ResourceManager.GetString("Fallo en la descarga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generando log.
        /// </summary>
        public static string Generando_log {
            get {
                return ResourceManager.GetString("Generando log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idiomas.
        /// </summary>
        public static string Idiomas {
            get {
                return ResourceManager.GetString("Idiomas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingles.
        /// </summary>
        public static string Ingles {
            get {
                return ResourceManager.GetString("Ingles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Integraciones.
        /// </summary>
        public static string Integraciones {
            get {
                return ResourceManager.GetString("Integraciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Integrar Miniatura.
        /// </summary>
        public static string Integrar_Miniatura {
            get {
                return ResourceManager.GetString("Integrar Miniatura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Integrar Subtitulos.
        /// </summary>
        public static string Integrar_Subtitulos {
            get {
                return ResourceManager.GetString("Integrar Subtitulos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introduce el nombre del preset.
        /// </summary>
        public static string Introduce_el_nombre_del_preset {
            get {
                return ResourceManager.GetString("Introduce el nombre del preset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lista Completa de opciones.
        /// </summary>
        public static string Lista_Completa_de_opciones {
            get {
                return ResourceManager.GetString("Lista Completa de opciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listo.
        /// </summary>
        public static string Listo {
            get {
                return ResourceManager.GetString("Listo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ahora al descargar videos, no aparecera la ventana.\nPara ver dicha informacion, mire el fichero de log ubicado en\n.
        /// </summary>
        public static string LogEnabledWarning {
            get {
                return ResourceManager.GetString("LogEnabledWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No he podido hacerlo mejor, y soy demasiado vago y quiero algo funcional.
        /// </summary>
        public static string MeBeingLazy {
            get {
                return ResourceManager.GetString("MeBeingLazy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre Repetido.
        /// </summary>
        public static string Nombre_Repetido {
            get {
                return ResourceManager.GetString("Nombre Repetido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El programa no puede encontrar la carpeta con todos los archivos necesarios para funcionar.\nAsegurate que la carpeta \&quot;youtube-dl\&quot; esta en la mismo directorio que este programa..
        /// </summary>
        public static string NoYTDLExmsg {
            get {
                return ResourceManager.GetString("NoYTDLExmsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Faltan Archivos.
        /// </summary>
        public static string NoYTDLExtitle {
            get {
                return ResourceManager.GetString("NoYTDLExtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Opciones.
        /// </summary>
        public static string Opciones {
            get {
                return ResourceManager.GetString("Opciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Opciones de lista.
        /// </summary>
        public static string Opciones_de_lista {
            get {
                return ResourceManager.GetString("Opciones de lista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Playlist.
        /// </summary>
        public static string Playlist {
            get {
                return ResourceManager.GetString("Playlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe un preset con ese nombre\nEscoja otro nombre.
        /// </summary>
        public static string PresetExists {
            get {
                return ResourceManager.GetString("PresetExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Presets.
        /// </summary>
        public static string Presets {
            get {
                return ResourceManager.GetString("Presets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona una carpeta de descargas\nPor defecto [Descargas].
        /// </summary>
        public static string SelectDownloadFolder {
            get {
                return ResourceManager.GetString("SelectDownloadFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Silencioso.
        /// </summary>
        public static string Silencioso {
            get {
                return ResourceManager.GetString("Silencioso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sitios Soportados.
        /// </summary>
        public static string Sitios_Soportados {
            get {
                return ResourceManager.GetString("Sitios Soportados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Terminar por:.
        /// </summary>
        public static string Terminar_por_ {
            get {
                return ResourceManager.GetString("Terminar por:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esta es una gran prueba NADA-NADA.
        /// </summary>
        public static string test {
            get {
                return ResourceManager.GetString("test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descargar un archivo con subtitulos.
        /// </summary>
        public static string TTDescargar_Subtitulos {
            get {
                return ResourceManager.GetString("TTDescargar_Subtitulos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se usara la miniatura del video como miniatura del archivo.
        /// </summary>
        public static string TTDescargarMiniaturas {
            get {
                return ResourceManager.GetString("TTDescargarMiniaturas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Integra la minuatura dentro del propio video descargado (Solo MP3 y MP4).
        /// </summary>
        public static string TTIntegrar_Miniatura {
            get {
                return ResourceManager.GetString("TTIntegrar_Miniatura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Integrara los subitulos dentro del video (Solo Ciertos formatos).
        /// </summary>
        public static string TTIntegrar_Subtitulos {
            get {
                return ResourceManager.GetString("TTIntegrar_Subtitulos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Evita que aparezca la interfaz de comandos.
        /// </summary>
        public static string TTSilencioso {
            get {
                return ResourceManager.GetString("TTSilencioso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Abrira un explorador web.
        /// </summary>
        public static string TTSitiosSoportados {
            get {
                return ResourceManager.GetString("TTSitiosSoportados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Click Derecho para pegar.
        /// </summary>
        public static string TTURL {
            get {
                return ResourceManager.GetString("TTURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a URL:.
        /// </summary>
        public static string URL_ {
            get {
                return ResourceManager.GetString("URL:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usar.
        /// </summary>
        public static string Usar {
            get {
                return ResourceManager.GetString("Usar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usar como predeterminada.
        /// </summary>
        public static string Usar_como_predeterminada {
            get {
                return ResourceManager.GetString("Usar como predeterminada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver Comando Final.
        /// </summary>
        public static string Ver_Comando_Final {
            get {
                return ResourceManager.GetString("Ver Comando Final", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
